# Generated by Django 5.2.9 on 2026-01-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('original_symbol', models.CharField(max_length=100)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='scanner.exchange')),
            ],
            options={
                'unique_together': {('exchange', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('period_hours', models.IntegerField(default=1)),
                ('apr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rates', to='scanner.ticker')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='scanner_fun_ticker__f40e23_idx')],
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
    ]
