# Generated by Django 5.2.9 on 2026-01-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Универсальный символ (BTC, ETH)', max_length=20, unique=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticker',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickers', to='scanner.asset'),
        ),
    ]
