# Generated by Django 5.2.9 on 2026-01-31 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitragePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usdt', models.DecimalField(decimal_places=2, help_text='Общая сумма позиции в USDT', max_digits=20)),
                ('long_entry_target', models.DecimalField(blank=True, decimal_places=8, help_text='Цена входа (если пусто - по рынку)', max_digits=20, null=True)),
                ('long_exit_target', models.DecimalField(blank=True, decimal_places=8, help_text='Тейк профит для лонга', max_digits=20, null=True)),
                ('short_entry_target', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('short_exit_target', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('realized_entry_long', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('realized_entry_short', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Entry'), ('ACTIVE', 'Active'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('long_ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='long_positions', to='scanner.ticker')),
                ('short_ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_positions', to='scanner.ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
