# Generated by Django 5.2.9 on 2026-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_arbitrageposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrageposition',
            name='amount_usdt',
        ),
        migrations.AddField(
            model_name='arbitrageposition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма позиции в USDT', max_digits=20, null=True),
        ),
    ]
